databases:
  - name: boualam
    plan: free
    databaseName: API_DB
    user: mysite

services:
  - type: web
    plan: free
    name: restapi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn HubspotApiIntegration.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: boualam
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
