# Generated by Django 5.1.3 on 2024-12-05 13:13

import authapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authapp.models.UserManager()),
            ],
        ),
    ]
