# Generated by Django 5.1.3 on 2024-12-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="terms_cond",
        ),
    ]
